[package]
name = "client"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

# [[bin]]
# name = "app"
# path = "src/bin/app.rs"

# [[bin]]
# name = "worker"
# path = "src/bin/worker.rs"

[dependencies]
console_error_panic_hook = "0.1.7"
ed25519-dalek = { workspace = true }
x25519-dalek = { workspace = true }
bitcode = { workspace = true }
futures = "0.3.33"
shared = { path = "../shared" }
gloo-net = "0.7.0"
gloo-timers = { version = "0.4.0", features = ["futures"] }
obfstr = "0.4.6"
wasm-bindgen = "0.2.126"
wasm-bindgen-futures = "0.4.76"
tokio = { version = "1", features = ["rt", "sync", "time", "macros"] }
tokio_with_wasm = { version = "0.9.0", features = ["rt", "sync", "time", "macros"] }
wgpu = { version = "30.0.0", features = ["webgl"]}
console_log = "1.1.0"
log = "0.4.33"
winit = { version = "0.30", features = ["android-native-activity"] }
glam = "0.33.2"
bytemuck = { version = "1.25.2", features = ["derive"] }
js-sys = "0.3.103"
glyphon = "0.12.0"
chacha20poly1305 = { workspace = true }
hkdf = { workspace = true }
sha2 = { workspace = true }
getrandom = { version = "0.4.3", features = ["wasm_js"] }

[dependencies.web-sys]
version = "0.3.103"
features = [
    "Document",
    "Element",
    "HtmlCanvasElement",
    "HtmlInputElement",
    "Window",
    "Performance",
    "Crypto",
    "EventTarget",
]

[dependencies.image]
version = "0.25.10"
default-features = false
features = ["png", "jpeg"]

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
