[workspace]
members = ["server", "client", "shared", "tt"]
resolver = "3"

package.authors = ["Gurmehar Singh"]
package.github = "https://github.com/gurmehar-singh-2009/nara.io"
package.license-file = "LICENSE.md"

[workspace.dependencies]
bytes = { version = "1.12.1", features = ["serde"] }
bitcode = { version = "0.6.9", features = ["derive", "serde"] }
snafu = "0.9.1"
hkdf = "0.13.0"
sha2 = "0.11.0"
x25519-dalek = { version = "3.0.0", features = ["static_secrets", "zeroize", "precomputed-tables"] }
ed25519-dalek = { version = "3.0.0", features = ["rand_core"] }
chacha20poly1305 = "0.11.0"
mlua = { version = "0.12", features = ["lua55", "vendored", "async", "send"] }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
debug = false
overflow-checks = false
incremental = false
panic = "abort"
strip = "debuginfo"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }

nursery = { level = "deny", priority = -1 }

cargo = { level = "deny", priority = -1 }

missing_docs_in_private_items = "warn"
todo = "deny"
unimplemented = "deny"
print_stdout = "warn"
print_stderr = "warn"
