-- Battleship (converted from tank_defs.json)
-- units are game units (tank body = 42), angles are degrees.
return {
    id = 48,
    name = "Battleship",
    upgradeMessage = "",
    levelRequirement = 45,
    upgrades = {},
    speed = 1,
    maxHealth = 50,
    sides = 1,
    fieldFactor = 0.899,
    absorbtionFactor = 1,
    preAddon = 0,
    postAddon = 0,
    flags = {
        invisibility = false,
        zoomAbility = false,
        canShoot = true,
        devOnly = false,
    },
    stats = {
        { name = "Movement Speed", max = 7 },
        { name = "Reload", max = 7 },
        { name = "Bullet Damage", max = 7 },
        { name = "Bullet Penetration", max = 7 },
        { name = "Bullet Speed", max = 7 },
        { name = "Body Damage", max = 7 },
        { name = "Max Health", max = 7 },
        { name = "Health Regen", max = 7 },
    },
    barrels = {
        {
            x = 0,
            y = -8.4,
            angle = 90,
            width = 12.3304,
            length = 31.5,
            delay = 0,
            reload = 1,
            recoil = 1,
            isTrapezoid = true,
            trapezoidDirection = 3.1416,
            addon = 0,
            droneCount = 4294967295,
            bullet = {
                type = "drone",
                health = 1,
                damage = 0.15,
                speed = 1,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = -8.4,
            angle = 270,
            width = 12.3304,
            length = 31.5,
            delay = 0,
            reload = 1,
            recoil = 1,
            isTrapezoid = true,
            trapezoidDirection = 3.1416,
            addon = 0,
            droneCount = 4294967295,
            bullet = {
                type = "drone",
                health = 1,
                damage = 0.15,
                speed = 1,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 8.4,
            angle = 90,
            width = 12.3304,
            length = 31.5,
            delay = 0,
            reload = 1,
            recoil = 1,
            isTrapezoid = true,
            trapezoidDirection = 3.1416,
            addon = 0,
            droneCount = 4294967295,
            bullet = {
                type = "drone",
                health = 1,
                damage = 0.15,
                speed = 1,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 8.4,
            angle = 270,
            width = 12.3304,
            length = 31.5,
            delay = 0,
            reload = 1,
            recoil = 1,
            isTrapezoid = true,
            trapezoidDirection = 3.1416,
            addon = 0,
            droneCount = 4294967295,
            bullet = {
                type = "drone",
                health = 1,
                damage = 0.15,
                speed = 1,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
    },
    onShoot = function(player)
        -- TODO
    end,
}
