-- Dominator (converted from tank_defs.json)
-- units are game units (tank body = 42), angles are degrees.
return {
    id = 47,
    name = "Dominator",
    upgradeMessage = "",
    levelRequirement = 0,
    upgrades = {},
    speed = 1,
    maxHealth = 6000,
    sides = 1,
    fieldFactor = 1,
    absorbtionFactor = 1,
    preAddon = 95,
    postAddon = 0,
    flags = {
        invisibility = false,
        zoomAbility = false,
        canShoot = true,
        devOnly = true,
    },
    stats = {
        { name = "Movement Speed", max = 0 },
        { name = "Reload", max = 0 },
        { name = "Bullet Damage", max = 0 },
        { name = "Bullet Penetration", max = 0 },
        { name = "Bullet Speed", max = 0 },
        { name = "Body Damage", max = 0 },
        { name = "Max Health", max = 0 },
        { name = "Health Regen", max = 0 },
    },
    barrels = {
        {
            x = 0,
            y = 0,
            angle = 0,
            width = 8.82,
            length = 25.2,
            delay = 0,
            reload = 1.5,
            recoil = 0,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 83,
            bullet = {
                type = "trap",
                health = 20,
                damage = 3,
                speed = 4,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 45,
            width = 8.82,
            length = 25.2,
            delay = 0,
            reload = 1.5,
            recoil = 0,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 83,
            bullet = {
                type = "trap",
                health = 20,
                damage = 3,
                speed = 4,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 90,
            width = 8.82,
            length = 25.2,
            delay = 0,
            reload = 1.5,
            recoil = 0,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 83,
            bullet = {
                type = "trap",
                health = 20,
                damage = 3,
                speed = 4,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 135,
            width = 8.82,
            length = 25.2,
            delay = 0,
            reload = 1.5,
            recoil = 0,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 83,
            bullet = {
                type = "trap",
                health = 20,
                damage = 3,
                speed = 4,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 180,
            width = 8.82,
            length = 25.2,
            delay = 0,
            reload = 1.5,
            recoil = 0,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 83,
            bullet = {
                type = "trap",
                health = 20,
                damage = 3,
                speed = 4,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 224.5,
            width = 8.82,
            length = 25.2,
            delay = 0,
            reload = 1.5,
            recoil = 0,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 83,
            bullet = {
                type = "trap",
                health = 20,
                damage = 3,
                speed = 4,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 270,
            width = 8.82,
            length = 25.2,
            delay = 0,
            reload = 1.5,
            recoil = 0,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 83,
            bullet = {
                type = "trap",
                health = 20,
                damage = 3,
                speed = 4,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 314.5,
            width = 8.82,
            length = 25.2,
            delay = 0,
            reload = 1.5,
            recoil = 0,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 83,
            bullet = {
                type = "trap",
                health = 20,
                damage = 3,
                speed = 4,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
    },
    onShoot = function(player)
        -- TODO
    end,
}
