-- Gunner (converted from tank_defs.json)
-- units are game units (tank body = 42), angles are degrees.
return {
    id = 20,
    name = "Gunner",
    upgradeMessage = "",
    levelRequirement = 30,
    upgrades = {
        "auto_gunner",
        "gunner_trapper",
        "streamliner",
    },
    speed = 1,
    maxHealth = 50,
    sides = 1,
    fieldFactor = 1,
    absorbtionFactor = 1,
    preAddon = 0,
    postAddon = 0,
    flags = {
        invisibility = false,
        zoomAbility = false,
        canShoot = true,
        devOnly = false,
    },
    stats = {
        { name = "Movement Speed", max = 7 },
        { name = "Reload", max = 7 },
        { name = "Bullet Damage", max = 7 },
        { name = "Bullet Penetration", max = 7 },
        { name = "Bullet Speed", max = 7 },
        { name = "Body Damage", max = 7 },
        { name = "Max Health", max = 7 },
        { name = "Health Regen", max = 7 },
    },
    barrels = {
        {
            x = 0,
            y = -13.44,
            angle = 0,
            width = 10.584,
            length = 27.3,
            delay = 0.5,
            reload = 1,
            recoil = 0.2,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 0,
            bullet = {
                type = "bullet",
                health = 0.449,
                damage = 0.5,
                speed = 1.1,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 13.44,
            angle = 0,
            width = 10.584,
            length = 27.3,
            delay = 0.75,
            reload = 1,
            recoil = 0.2,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 0,
            bullet = {
                type = "bullet",
                health = 0.449,
                damage = 0.5,
                speed = 1.1,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = -7.14,
            angle = 0,
            width = 10.584,
            length = 35.7,
            delay = 0,
            reload = 1,
            recoil = 0.2,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 0,
            bullet = {
                type = "bullet",
                health = 0.449,
                damage = 0.5,
                speed = 1.1,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 7.14,
            angle = 0,
            width = 10.584,
            length = 35.7,
            delay = 0.25,
            reload = 1,
            recoil = 0.2,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 0,
            bullet = {
                type = "bullet",
                health = 0.449,
                damage = 0.5,
                speed = 1.1,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
    },
    onShoot = function(player)
        -- TODO
    end,
}
