-- Mega Trapper (converted from tank_defs.json)
-- units are game units (tank body = 42), angles are degrees.
return {
    id = 34,
    name = "Mega Trapper",
    upgradeMessage = "",
    levelRequirement = 45,
    upgrades = {},
    speed = 1,
    maxHealth = 50,
    sides = 1,
    fieldFactor = 0.899,
    absorbtionFactor = 1,
    preAddon = 0,
    postAddon = 0,
    flags = {
        invisibility = false,
        zoomAbility = false,
        canShoot = true,
        devOnly = false,
    },
    stats = {
        { name = "Movement Speed", max = 7 },
        { name = "Reload", max = 7 },
        { name = "Bullet Damage", max = 7 },
        { name = "Bullet Penetration", max = 7 },
        { name = "Bullet Speed", max = 7 },
        { name = "Body Damage", max = 7 },
        { name = "Max Health", max = 7 },
        { name = "Health Regen", max = 7 },
    },
    barrels = {
        {
            x = 0,
            y = 0,
            angle = 0,
            width = 22.9144,
            length = 25.2,
            delay = 0,
            reload = 3.3,
            recoil = 1,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 83,
            bullet = {
                type = "trap",
                health = 3.2,
                damage = 1.6,
                speed = 2,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
    },
    onShoot = function(player)
        -- TODO
    end,
}
