-- Mothership (converted from tank_defs.json)
-- units are game units (tank body = 42), angles are degrees.
return {
    id = 27,
    name = "Mothership",
    upgradeMessage = "",
    levelRequirement = 0,
    upgrades = {},
    speed = 1,
    maxHealth = 50,
    sides = 16,
    fieldFactor = 1,
    absorbtionFactor = 0.009,
    preAddon = 0,
    postAddon = 0,
    flags = {
        invisibility = false,
        zoomAbility = false,
        canShoot = true,
        devOnly = true,
    },
    stats = {
        { name = "Movement Speed", max = 7 },
        { name = "Reload", max = 7 },
        { name = "Drone Damage", max = 7 },
        { name = "Drone Health", max = 7 },
        { name = "Drone Speed", max = 7 },
        { name = "Body Damage", max = 7 },
        { name = "Max Health", max = 7 },
        { name = "Health Regen", max = 7 },
    },
    barrels = {
        {
            x = 0,
            y = 0,
            angle = 11,
            width = 4.41,
            length = 25.2,
            delay = 0,
            reload = 6,
            recoil = 0,
            isTrapezoid = true,
            trapezoidDirection = 0,
            addon = 0,
            droneCount = 2,
            bullet = {
                type = "drone",
                health = 2,
                damage = 0.699,
                speed = 0.48,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 33.5,
            width = 4.41,
            length = 25.2,
            delay = 0,
            reload = 6,
            recoil = 0,
            isTrapezoid = true,
            trapezoidDirection = 0,
            addon = 0,
            droneCount = 2,
            bullet = {
                type = "drone",
                health = 2,
                damage = 0.699,
                speed = 0.48,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 56,
            width = 4.41,
            length = 25.2,
            delay = 0,
            reload = 6,
            recoil = 0,
            isTrapezoid = true,
            trapezoidDirection = 0,
            addon = 0,
            droneCount = 2,
            bullet = {
                type = "drone",
                health = 2,
                damage = 0.699,
                speed = 0.48,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 78.5,
            width = 4.41,
            length = 25.2,
            delay = 0,
            reload = 6,
            recoil = 0,
            isTrapezoid = true,
            trapezoidDirection = 0,
            addon = 0,
            droneCount = 2,
            bullet = {
                type = "drone",
                health = 2,
                damage = 0.699,
                speed = 0.48,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 101,
            width = 4.41,
            length = 25.2,
            delay = 0,
            reload = 6,
            recoil = 0,
            isTrapezoid = true,
            trapezoidDirection = 0,
            addon = 0,
            droneCount = 2,
            bullet = {
                type = "drone",
                health = 2,
                damage = 0.699,
                speed = 0.48,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 123.5,
            width = 4.41,
            length = 25.2,
            delay = 0,
            reload = 6,
            recoil = 0,
            isTrapezoid = true,
            trapezoidDirection = 0,
            addon = 0,
            droneCount = 2,
            bullet = {
                type = "drone",
                health = 2,
                damage = 0.699,
                speed = 0.48,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 146,
            width = 4.41,
            length = 25.2,
            delay = 0,
            reload = 6,
            recoil = 0,
            isTrapezoid = true,
            trapezoidDirection = 0,
            addon = 0,
            droneCount = 2,
            bullet = {
                type = "drone",
                health = 2,
                damage = 0.699,
                speed = 0.48,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 168.5,
            width = 4.41,
            length = 25.2,
            delay = 0,
            reload = 6,
            recoil = 0,
            isTrapezoid = true,
            trapezoidDirection = 0,
            addon = 0,
            droneCount = 2,
            bullet = {
                type = "drone",
                health = 2,
                damage = 0.699,
                speed = 0.48,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 191,
            width = 4.41,
            length = 25.2,
            delay = 0,
            reload = 6,
            recoil = 0,
            isTrapezoid = true,
            trapezoidDirection = 0,
            addon = 0,
            droneCount = 2,
            bullet = {
                type = "drone",
                health = 2,
                damage = 0.699,
                speed = 0.48,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 213.5,
            width = 4.41,
            length = 25.2,
            delay = 0,
            reload = 6,
            recoil = 0,
            isTrapezoid = true,
            trapezoidDirection = 0,
            addon = 0,
            droneCount = 2,
            bullet = {
                type = "drone",
                health = 2,
                damage = 0.699,
                speed = 0.48,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 236,
            width = 4.41,
            length = 25.2,
            delay = 0,
            reload = 6,
            recoil = 0,
            isTrapezoid = true,
            trapezoidDirection = 0,
            addon = 0,
            droneCount = 2,
            bullet = {
                type = "drone",
                health = 2,
                damage = 0.699,
                speed = 0.48,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 258.5,
            width = 4.41,
            length = 25.2,
            delay = 0,
            reload = 6,
            recoil = 0,
            isTrapezoid = true,
            trapezoidDirection = 0,
            addon = 0,
            droneCount = 2,
            bullet = {
                type = "drone",
                health = 2,
                damage = 0.699,
                speed = 0.48,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 281,
            width = 4.41,
            length = 25.2,
            delay = 0,
            reload = 6,
            recoil = 0,
            isTrapezoid = true,
            trapezoidDirection = 0,
            addon = 0,
            droneCount = 2,
            bullet = {
                type = "drone",
                health = 2,
                damage = 0.699,
                speed = 0.48,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 303.5,
            width = 4.41,
            length = 25.2,
            delay = 0,
            reload = 6,
            recoil = 0,
            isTrapezoid = true,
            trapezoidDirection = 0,
            addon = 0,
            droneCount = 2,
            bullet = {
                type = "drone",
                health = 2,
                damage = 0.699,
                speed = 0.48,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 326,
            width = 4.41,
            length = 25.2,
            delay = 0,
            reload = 6,
            recoil = 0,
            isTrapezoid = true,
            trapezoidDirection = 0,
            addon = 0,
            droneCount = 2,
            bullet = {
                type = "drone",
                health = 2,
                damage = 0.699,
                speed = 0.48,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 348.5,
            width = 4.41,
            length = 25.2,
            delay = 0,
            reload = 6,
            recoil = 0,
            isTrapezoid = true,
            trapezoidDirection = 0,
            addon = 0,
            droneCount = 2,
            bullet = {
                type = "drone",
                health = 2,
                damage = 0.699,
                speed = 0.48,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
    },
    onShoot = function(player)
        -- TODO
    end,
}
