-- Octo Tank (converted from tank_defs.json)
-- units are game units (tank body = 42), angles are degrees.
return {
    id = 5,
    name = "Octo Tank",
    upgradeMessage = "",
    levelRequirement = 45,
    upgrades = {},
    speed = 1,
    maxHealth = 50,
    sides = 1,
    fieldFactor = 1,
    absorbtionFactor = 1,
    preAddon = 0,
    postAddon = 0,
    flags = {
        invisibility = false,
        zoomAbility = false,
        canShoot = true,
        devOnly = false,
    },
    stats = {
        { name = "Movement Speed", max = 7 },
        { name = "Reload", max = 7 },
        { name = "Bullet Damage", max = 7 },
        { name = "Bullet Penetration", max = 7 },
        { name = "Bullet Speed", max = 7 },
        { name = "Body Damage", max = 7 },
        { name = "Max Health", max = 7 },
        { name = "Health Regen", max = 7 },
    },
    barrels = {
        {
            x = 0,
            y = 0,
            angle = -45.5,
            width = 17.64,
            length = 39.9,
            delay = 0.5,
            reload = 1,
            recoil = 1,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 0,
            bullet = {
                type = "bullet",
                health = 1,
                damage = 0.649,
                speed = 1,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 45,
            width = 17.64,
            length = 39.9,
            delay = 0.5,
            reload = 1,
            recoil = 1,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 0,
            bullet = {
                type = "bullet",
                health = 1,
                damage = 0.649,
                speed = 1,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = -135.5,
            width = 17.64,
            length = 39.9,
            delay = 0.5,
            reload = 1,
            recoil = 1,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 0,
            bullet = {
                type = "bullet",
                health = 1,
                damage = 0.649,
                speed = 1,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 135,
            width = 17.64,
            length = 39.9,
            delay = 0.5,
            reload = 1,
            recoil = 1,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 0,
            bullet = {
                type = "bullet",
                health = 1,
                damage = 0.649,
                speed = 1,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 180,
            width = 17.64,
            length = 39.9,
            delay = 0,
            reload = 1,
            recoil = 1,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 0,
            bullet = {
                type = "bullet",
                health = 1,
                damage = 0.649,
                speed = 1,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = -90.5,
            width = 17.64,
            length = 39.9,
            delay = 0,
            reload = 1,
            recoil = 1,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 0,
            bullet = {
                type = "bullet",
                health = 1,
                damage = 0.649,
                speed = 1,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 90,
            width = 17.64,
            length = 39.9,
            delay = 0,
            reload = 1,
            recoil = 1,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 0,
            bullet = {
                type = "bullet",
                health = 1,
                damage = 0.649,
                speed = 1,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 0,
            width = 17.64,
            length = 39.9,
            delay = 0,
            reload = 1,
            recoil = 1,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 0,
            bullet = {
                type = "bullet",
                health = 1,
                damage = 0.649,
                speed = 1,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
    },
    onShoot = function(player)
        -- TODO
    end,
}
