-- Predator (converted from tank_defs.json)
-- units are game units (tank body = 42), angles are degrees.
return {
    id = 28,
    name = "Predator",
    upgradeMessage = "Use your right mouse button to look further in the direction you're facing",
    levelRequirement = 45,
    upgrades = {},
    speed = 1,
    maxHealth = 50,
    sides = 1,
    fieldFactor = 0.85,
    absorbtionFactor = 1,
    preAddon = 0,
    postAddon = 0,
    flags = {
        invisibility = false,
        zoomAbility = true,
        canShoot = true,
        devOnly = false,
    },
    stats = {
        { name = "Movement Speed", max = 7 },
        { name = "Reload", max = 7 },
        { name = "Bullet Damage", max = 7 },
        { name = "Bullet Penetration", max = 7 },
        { name = "Bullet Speed", max = 7 },
        { name = "Body Damage", max = 7 },
        { name = "Max Health", max = 7 },
        { name = "Health Regen", max = 7 },
    },
    barrels = {
        {
            x = 0,
            y = 0,
            angle = 0,
            width = 17.64,
            length = 46.2,
            delay = 0,
            reload = 3,
            recoil = 0.3,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 0,
            bullet = {
                type = "bullet",
                health = 1,
                damage = 0.75,
                speed = 1.399,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 0,
            width = 23.814,
            length = 39.9,
            delay = 0.2,
            reload = 3,
            recoil = 0.3,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 0,
            bullet = {
                type = "bullet",
                health = 1,
                damage = 0.75,
                speed = 1.399,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
        {
            x = 0,
            y = 0,
            angle = 0,
            width = 29.988,
            length = 33.6,
            delay = 0.4,
            reload = 3,
            recoil = 0.3,
            isTrapezoid = false,
            trapezoidDirection = 0,
            addon = 0,
            bullet = {
                type = "bullet",
                health = 1,
                damage = 0.75,
                speed = 1.399,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
    },
    onShoot = function(player)
        -- TODO
    end,
}
