-- Rocketeer (converted from tank_defs.json)
-- units are game units (tank body = 42), angles are degrees.
return {
    id = 55,
    name = "Rocketeer",
    upgradeMessage = "",
    levelRequirement = 45,
    upgrades = {},
    speed = 1,
    maxHealth = 50,
    sides = 1,
    fieldFactor = 0.899,
    absorbtionFactor = 1,
    preAddon = 94,
    postAddon = 0,
    flags = {
        invisibility = false,
        zoomAbility = false,
        canShoot = true,
        devOnly = false,
    },
    stats = {
        { name = "Movement Speed", max = 7 },
        { name = "Reload", max = 7 },
        { name = "Bullet Damage", max = 7 },
        { name = "Bullet Penetration", max = 7 },
        { name = "Bullet Speed", max = 7 },
        { name = "Body Damage", max = 7 },
        { name = "Max Health", max = 7 },
        { name = "Health Regen", max = 7 },
    },
    barrels = {
        {
            x = 0,
            y = 0,
            angle = 0,
            width = 22.05,
            length = 33.6,
            delay = 0,
            reload = 4,
            recoil = 3,
            isTrapezoid = true,
            trapezoidDirection = 3.1416,
            addon = 0,
            bullet = {
                type = "bullet",
                health = 5,
                damage = 1,
                speed = 0.3,
                scatterRate = 1,
                lifeLength = 1,
                absorbtionFactor = 1,
                sizeRatio = 1,
            },
        },
    },
    onShoot = function(player)
        -- TODO
    end,
}
